export const COLORS = [
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#22c55e",
  "#10b981",
  "#3b82f6",
  "#6366f1",
  "#8b5cf6",
  "#ec4899",
  "#14b8a6",
  "#0ea5e9",
  "#f43f5e",
  "#1e293b",
  "#475569",
  "#e2e8f0",
];

export const FONTS = [
  { label: "Default", value: "" },
  { label: "Serif", value: "Georgia, serif" },
  { label: "Mono", value: "'Courier New', monospace" },
  { label: "Cursive", value: "cursive" },
  { label: "System", value: "system-ui, sans-serif" },
  { label: "Nunito", value: "'Nunito', sans-serif" },
];

export const SIZES = ["10", "11", "12", "13", "14", "16", "18", "20", "22", "24", "28", "32", "36", "48", "64"];

export const MATH_SYMS = [
  { label: "√", ins: "√" },
  { label: "∑", ins: "∑" },
  { label: "∫", ins: "∫" },
  { label: "∂", ins: "∂" },
  { label: "∞", ins: "∞" },
  { label: "π", ins: "π" },
  { label: "±", ins: "±" },
  { label: "≤", ins: "≤" },
  { label: "≥", ins: "≥" },
  { label: "≠", ins: "≠" },
  { label: "≈", ins: "≈" },
  { label: "∈", ins: "∈" },
  { label: "∉", ins: "∉" },
  { label: "∩", ins: "∩" },
  { label: "∪", ins: "∪" },
  { label: "⊂", ins: "⊂" },
  { label: "⊆", ins: "⊆" },
  { label: "∀", ins: "∀" },
  { label: "∃", ins: "∃" },
  { label: "¬", ins: "¬" },
  { label: "→", ins: "→" },
  { label: "↔", ins: "↔" },
  { label: "⇒", ins: "⇒" },
  { label: "⇔", ins: "⇔" },
  { label: "α", ins: "α" },
  { label: "β", ins: "β" },
  { label: "γ", ins: "γ" },
  { label: "δ", ins: "δ" },
  { label: "θ", ins: "θ" },
  { label: "λ", ins: "λ" },
  { label: "μ", ins: "μ" },
  { label: "σ", ins: "σ" },
  { label: "φ", ins: "φ" },
  { label: "ω", ins: "ω" },
  { label: "Δ", ins: "Δ" },
  { label: "Σ", ins: "Σ" },
  { label: "Π", ins: "Π" },
  { label: "Ω", ins: "Ω" },
  { label: "²", ins: "²" },
  { label: "³", ins: "³" },
  { label: "½", ins: "½" },
  { label: "¼", ins: "¼" },
];
